DEF_STR_PARAM_(QUESTION_FORMAT_STR       , L"Загаданный объект %ls? (Y/n)")
DEF_STR_PARAM_(ADD_OBJECT_FORMAT_STR     , L"У меня нет идей. Что же вы загадали?")
DEF_STR_PARAM_(OBJECT_DIFFER_FORMAT_STR  , L"Бро, чем %ls отличается от %ls?")
DEF_STR_PARAM_(BAD_INPUT_FORMAT_STR      , L"Какой-то неровный базар у тебя. Ответь нормально -_-")
DEF_STR_PARAM_(CORRECT_GUESS_FORMAT_STR  , L"Очев\n")
DEF_STR_PARAM_(PLAY_AGAIN_FORMAT_STR     , L"Хотите сыграть ещё? (Y/n)")
DEF_STR_PARAM_(SAVE_DATA_FORMAT_STR      , L"Сохранить прогресс? (Y/n)")

DEF_STR_PARAM_(ENTER_LABELS_FORMAT_STR   , L"Введите названия объектов")
DEF_STR_PARAM_(SUBMIT_BUTTON_LABEL       , L"Отправить")
DEF_STR_PARAM_(YES_BUTTON_LABEL          , L"Да")
DEF_STR_PARAM_(NO_BUTTON_LABEL           , L"Нет")
DEF_STR_PARAM_(GIVE_DEFINITION_LABEL     , L"Дать определение")
DEF_STR_PARAM_(GIVE_COMPARISON_LABEL     , L"Сравнить объекты")
DEF_STR_PARAM_(NO_LABEL_FORMAT_STR       , L"Я не знаю, что такое %ls")
DEF_STR_PARAM_(COMPARE_FORMAT_STR        , L"%ls отличается от %ls тем, что ")
DEF_STR_PARAM_(COMPARE_SIMILAR_FORMAT_STR, L"\nИх общие черты ")
